name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -count=500 ./...

    - name: Test GOAMD64=v3
      run: go test -count=500 ./...
      env:
        GOAMD64: v3

    - name: Test purego
      run: go test -count=500 -tags purego ./...

    - name: Build for GOARCH=arm64
      run: go build -v ./...
      env:
        GOARCH: arm64
